require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'app/views/**/*'
    - 'config/environments/*'

Style/Documentation:
  Enabled: false

GemSpec/RequiredRubyVersion:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Style/OpenStructUse:
  Exclude:
    - "**/*_spec.rb"

