# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in users.gemspec.
gemspec

gem 'debug'
gem 'pg', '~> 1.3.5'
gem 'sprockets-rails'
